export { default as Hero } from "./Hero";
export { default as Projects } from "./Projects";
export { default as Navbar } from "./Navbar";
export { default as Skills } from "./Skills";
export { default as About } from "./About";
export { default as Work } from "./Work";
export { default as Contact } from "./Contact";
export { default as ThemeToggle } from "./ThemeToggle";
export { default as Footer } from "./Footer";
